### PR TITLE
No next

### PR DESCRIPTION
**Pull request by OwenArnold**
https://github.com/scipp/scipp/issues/2074

### CODE REVIEW

**Review by nvaytet — CHANGES_REQUESTED** [review]
We should also remove the `ess-developer-next.yml` and `ess-developer-dev.yml` files to only have one env file left?

**Comment by nvaytet** [comment]
@OwenArnold I made some additional changes. Can you double-check? Thanks.

**Comment by SimonHeybrock** [comment]
Should we try to get this merged? There is also a conflict.

**Review by nvaytet — APPROVED** [review]
@OwenArnold , can you have a second look since I also made changes in this PR?

**Pull request merged**
